http:
  port: :8081

log: 
  enable_to_console: true
  to_console_level: debug # debug / info / warn / error / dpanic / panic / fatal
  to_file_level: debug
  filename: ./_logs/dev.log
  max_size: 10 #MB
  max_age: 3 #days
  max_backups: 7

persistence:
  mysql:
    dsn: root:admin123@tcp(localhost:3306)/go-gin-template?charset=utf8mb4&parseTime=true
  postgres:
    dsn: root:admin123@tcp(localhost:3306)/go-gin-template?charset=utf8mb4&parseTime=true

auth:
  jwt:
    secret_key: go-template
    access_token_expiry: 15m
    refresh_token_expiry: 168h
    issuer: lyon.nee