http:
  port: :80

log: 
  format: "json"        # 输出格式，console 或 json，默认是 console
  caller: "short"          # 输出文件路径，full 或 short，默认是 full
  level: info # debug / info / warn / error / dpanic / panic / fatal
  to_file: true
  log_file_config:
    filename: ./_logs/test.log
    log_level: info
    max_size: 10 # 最大文件大小(MB)，默认值10MB
    max_age: 7 # 保留旧文件的最大天数，默认值3天
    max_backups: 64 # 保留旧文件的最大个数，默认值100个
    isCompression: false # 是否压缩

persistence:
  mysql:
    dsn: root:admin123@tcp(localhost:3306)/go-gin-template?charset=utf8mb4&parseTime=true
  postgres:
    dsn: root:admin123@tcp(localhost:3306)/go-gin-template?charset=utf8mb4&parseTime=true

auth:
  jwt:
    secret_key: go-template
    access_token_expiry: 15m
    refresh_token_expiry: 7d
    issuer: lyon.nee