// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/interfaces/grpc/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户基础信息
type UserBasic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBasic) Reset() {
	*x = UserBasic{}
	mi := &file_internal_interfaces_grpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBasic) ProtoMessage() {}

func (x *UserBasic) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_grpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBasic.ProtoReflect.Descriptor instead.
func (*UserBasic) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserBasic) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserBasic) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserBasic) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserBasic) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserBasic) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserBasic) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_internal_interfaces_grpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_grpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserBasic             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_internal_interfaces_grpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_grpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserResponse) GetUser() *UserBasic {
	if x != nil {
		return x.User
	}
	return nil
}

var File_internal_interfaces_grpc_user_proto protoreflect.FileDescriptor

const file_internal_interfaces_grpc_user_proto_rawDesc = "" +
	"\n" +
	"#internal/interfaces/grpc/user.proto\x12\x06userpb\"\xa1\x01\n" +
	"\tUserBasic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"8\n" +
	"\x0fGetUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.userpb.UserBasicR\x04user2I\n" +
	"\vUserService\x12:\n" +
	"\aGetUser\x12\x16.userpb.GetUserRequest\x1a\x17.userpb.GetUserResponseB@Z>github.com/lyonnee/go-template/internal/interfaces/grpc/userpbb\x06proto3"

var (
	file_internal_interfaces_grpc_user_proto_rawDescOnce sync.Once
	file_internal_interfaces_grpc_user_proto_rawDescData []byte
)

func file_internal_interfaces_grpc_user_proto_rawDescGZIP() []byte {
	file_internal_interfaces_grpc_user_proto_rawDescOnce.Do(func() {
		file_internal_interfaces_grpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_interfaces_grpc_user_proto_rawDesc), len(file_internal_interfaces_grpc_user_proto_rawDesc)))
	})
	return file_internal_interfaces_grpc_user_proto_rawDescData
}

var file_internal_interfaces_grpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_interfaces_grpc_user_proto_goTypes = []any{
	(*UserBasic)(nil),       // 0: userpb.UserBasic
	(*GetUserRequest)(nil),  // 1: userpb.GetUserRequest
	(*GetUserResponse)(nil), // 2: userpb.GetUserResponse
}
var file_internal_interfaces_grpc_user_proto_depIdxs = []int32{
	0, // 0: userpb.GetUserResponse.user:type_name -> userpb.UserBasic
	1, // 1: userpb.UserService.GetUser:input_type -> userpb.GetUserRequest
	2, // 2: userpb.UserService.GetUser:output_type -> userpb.GetUserResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_interfaces_grpc_user_proto_init() }
func file_internal_interfaces_grpc_user_proto_init() {
	if File_internal_interfaces_grpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_interfaces_grpc_user_proto_rawDesc), len(file_internal_interfaces_grpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_interfaces_grpc_user_proto_goTypes,
		DependencyIndexes: file_internal_interfaces_grpc_user_proto_depIdxs,
		MessageInfos:      file_internal_interfaces_grpc_user_proto_msgTypes,
	}.Build()
	File_internal_interfaces_grpc_user_proto = out.File
	file_internal_interfaces_grpc_user_proto_goTypes = nil
	file_internal_interfaces_grpc_user_proto_depIdxs = nil
}
